### ISSUE TITLE
TILT, machine-readable privacy policies

### ISSUE THREAD

**Issue by eliasgruenewald** [jviotti/awesome-jsonschema#19]
### URL
https://github.com/Transparency-Information-Language/meta
https://github.com/Transparency-Information-Language/schema

### Summary
TILT is a transparency information language and toolkit powered by JSON Schema explicitly designed to represent and process transparency information in line with the requirements of the EU General Data Protection Regulation and allowing for a more automated and adaptive use of such information than established, legalese data protection policies do.

**Comment by jviotti** [comment]
@eliasgruenewald Awesome work. Thanks a lot for sharing! I added both the repository and the paper to the list. We would love to hear more about your work and your use of JSON Schema at the office hours (https://github.com/json-schema-org/community/discussions/34) if you ever have a chance to join :)
